inhibit_all_warnings!

target 'SimpleLamp' do

platform :ios, '9.0'

pod 'Masonry'
pod 'SDWebImage', '~> 5.0'
pod 'AFNetworking', '~> 3.0'
#pod 'IQKeyboardManager'
pod 'KMNavigationBarTransition'
pod 'MJRefresh', '~> 3.2.0'
pod 'YYModel'
pod 'CYLTabBarController', '~> 1.29.0'
pod 'MJExtension'
#pod 'ZJScrollPageView'
pod 'CHTCollectionViewWaterfallLayout'
pod 'FLAnimatedImage', '~> 1.0'



end

post_install do |installer|
  installer.pods_project.targets.each do |target|
 target.build_configurations.each do |config|
  if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
   end
  end
 end
end
